services:
    tahoe.multi_tenancy.invitation_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - Tahoe\Bundle\MultiTenancyBundle\Entity\Invitation

    invitation_repository:
        alias: tahoe.multi_tenancy.invitation_repository

    tahoe.multi_tenancy.tenant_user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - Tahoe\Bundle\MultiTenancyBundle\Entity\TenantUser

    tenant_user_repository:
        alias: tahoe.multi_tenancy.tenant_user_repository

    tenant_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - %tahoe_multi_tenancy.tenant.class%

    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - %tahoe_multi_tenancy.user.class%
